-- Ensure new columns exist for PortalUser added in recent auth hardening
ALTER TABLE PORTAL_USER ADD COLUMN IF NOT EXISTS FAILED_LOGIN_ATTEMPTS INT DEFAULT 0;
ALTER TABLE PORTAL_USER ADD COLUMN IF NOT EXISTS LOCKED_UNTIL TIMESTAMP;
ALTER TABLE PORTAL_USER ADD COLUMN IF NOT EXISTS VERIFICATION_TOKEN VARCHAR(255);
ALTER TABLE PORTAL_USER ADD COLUMN IF NOT EXISTS VERIFIED BOOLEAN DEFAULT FALSE;
ALTER TABLE PORTAL_USER ADD COLUMN IF NOT EXISTS COMPANY_NAME VARCHAR(255);

-- Existing local users were created with email-verification disabled in UI flow; unblock login.
UPDATE PORTAL_USER SET VERIFIED = TRUE WHERE VERIFIED IS NULL OR VERIFIED = FALSE;